# Generated by Django 5.1.7 on 2025-07-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('media', 'media')], default='text', max_length=20),
        ),
    ]
