# Generated by Django 5.1.7 on 2025-07-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'image'), ('video', 'video')], default='text', max_length=20),
        ),
    ]
